#!/bin/bash
# Set colors for bar / tray
bgcolor=$(xrdb -query | grep -E '^(URxvt|\*)(\*|\.)background' | sed -E "s/\[?[0-9]{0,3}\]?#/#/" | cut -d":" -f2 | tr -d "\t") #| sed 's/\[[0-9][0-9]\]#/#da/')
fgcolor=$(xrdb -query | grep -E '^(URxvt|\*)(\*|\.)foreground' | cut -d":" -f2 | tr -d "\t")
echo "bgcolor: $bgcolor, fgcolor: $fgcolor"

. lemonbar.conf
if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\\n" "The panel is already running." >&2
	exit 1
fi
source ~/.bashrc # runTray command won't work otherwise

# Make a named pipe to send all output from this script to
Pipe="/tmp/mybar.info"
[ -e "$Pipe" ] && rm "$Pipe"
mkfifo "$Pipe"

Volume() {
	while true
	do
		controls=$(pactl list sinks)
		vol=$(echo "$controls" | grep -e "Volume:" | grep -v "Base" | grep -oE "[0-9][0-9]*%" | head -n 1)
		mute=$(echo "$controls" | grep "Mute" | tr -d "\t " | cut -d":" -f2 | head -n 1)
		i="${vol::-1}" # removes last character of string
		if [[ "$mute" = 'no' ]]; then
			if [ $i -gt 50 ]; then
				echo -e "V\\uf028 $vol"
			elif [ $i -gt 0 ]; then
				echo -e "V\\uf027 $vol"
			else
				echo -e "V\\uf026 $vol"
			fi
		else
			echo -e "V\uf6a9 $vol\n"
		fi
		sleep 1
	done
}

Music() {
	var="$(queryRemoteServer.sh mpc -f "%artist%;%title%" current)" 
	curSong="/tmp/curSong.bar"
	curPID="/tmp/music.pid"
	size=60
	buffer="                                                                                             "
	while true
	do
		case "$var" in
			"")
				var="$(queryRemoteServer.sh mpc -f "%artist%;%title%" current)" 
				sleep 5
				;;
			"mpd error"*)
				var="$(queryRemoteServer.sh mpc -f "%artist%;%title%" current)" 
				sleep 5
				continue
				;;
			"not connected to"*)
				var=""
				sleep 5
				;;
			"Terminated"*)
				var="$(queryRemoteServer.sh mpc -f "%artist%;%title%" current)" 
				continue
				;;
		esac
		if ! [ "$var" == '' ]; then
			artist="$(echo "$var" | sed -E 's/(.*)\;.*/\1/g')"
			(( artistLen=${#artist})) ## length of artist on its own
			title="$(echo "$var" | sed -E 's/.*\;(.*)/\1/g')"
			(( titleLen=${#title})) ## length of title on its own
			total="$artist - $title"
			(( totalLen=${#total} )) ## length of artist and title with ' - ' separator inbetween
			if (( totalLen > size )); then
				## scrollingLen is the amount of characters that are out of view and have to be scrolled in
				(( scrollingLen = totalLen - size ))
				(( i=0 ))
				(( delay=0 )) # Used to prevent text from scrolling out of sight right away, improves readability
				queryRemoteServer.sh mpc -f "%artist%;%title%" current --wait > $curSong 2>&1 & 
				pidmpc=$!
				echo "$pidmpc" > "$curPID"
				while kill -0 $pidmpc 2> /dev/null
				do
					#if the artistlength is greater than the title, scroll the whole thing
					if (( artistLen > titleLen )); then 
						if (( i <= scrollingLen )); then
							musicInfo="${total:$i:$size}"
							if (( delay > 8 )); then (( i++ )); else (( delay++ )); fi
						else
							musicInfo="${total:$i}${buffer:0:((i - scrollingLen))}"
							(( i++ ))
							if (( i > totalLen )); then
								(( i=0 ))
								(( delay=0 ))
							fi
						fi
						echo -e "M| \\uf001 $musicInfo"
					#else scroll just the title, artist stays static
					else 
						if (( i <= scrollingLen )); then
							musicTitlePart="${title:$i:((size - artistLen - 3))}"
							if (( delay > 8 )); then (( i++ )); else (( delay++ )); fi
						else
							musicTitlePart="${title:$i}${buffer:0:((i - scrollingLen))}"
							(( i++ ))
							if (( i > ( totalLen - artistLen - 3 ) )); then
								(( i=0 ))
								(( delay=0 ))
							fi
						fi
						echo -e "M| \\uf001 $artist - $musicTitlePart"
					fi
					sleep 0.3
				done
				var="$(cat $curSong)"
			else
				queryRemoteServer.sh mpc -f "%artist%;%title%" current --wait > $curSong 2>&1 &
				pidmpc=$!
				echo "$pidmpc" > "$curPID"
				echo -e "M| \\uf001 $artist - $title"
				while kill -0 $pidmpc 2> /dev/null
				do
					wait
				done
				var="$(cat $curSong)"
			fi
		else
			echo "M"
			queryRemoteServer.sh mpc -f "%artist%;%title%" current --wait > $curSong 2>&1 & 
			pidmpc=$!
			echo "$pidmpc" > "$curPID"
			while kill -0 $pidmpc 2> /dev/null
			do
				wait
			done
			var="$(cat $curSong)"
		fi
	done
}

Battery() {
	while true
	do
		BATPRC=$(acpi --battery | cut -d" " -f4 | tr -d ",")
		#BATETA=$(acpi --battery | cut -d" " -f5)
		if   (( ${BATPRC::-1} > 90 )); then echo -e "B\\uf240 $BATPRC\n"
		elif (( ${BATPRC::-1} > 70 )); then echo -e "B\\uf241 $BATPRC\n"
		elif (( ${BATPRC::-1} > 40 )); then echo -e "B\\uf242 $BATPRC\n"
		elif (( ${BATPRC::-1} > 10 )); then echo -e "B\\uf243 $BATPRC\n"
		else echo -e "B\\uf244 $BATPRC\n"; fi
		echo -e "B\\uf242 $BATPRC\n"
		sleep 30
	done
}

xtitle -t 50 -sf "T%s\n" > "$Pipe" &
bspc subscribe report    > "$Pipe" &
bm_date_mod > "$Pipe" &
bm_disk_mod > "$Pipe" &
bm_ip_mod 	> "$Pipe" &
command -v acpi && Battery > "$Pipe" &
Volume  > "$Pipe" &
Music   > "$Pipe" &

MONITOR_WIDTH="$(xrandr | grep primary | sed -nE 's/^.*([0-9]{4})x[0-9]+\+[0-9]+\+[0-9]+.*$/\1/p')"
PANEL_WIDTH=$(( $MONITOR_WIDTH - 70 ))
lemonbar.input < "$Pipe" | lemonbar \
	-f "Font Awesome 5 Free Solid:pixelsize=11:minspace=true:antialias=true" \
	-f "Misc Ohsnapu:pixelsize=13:antialias=false:minspace=true:spacing=110" \
	-f "basis33:pixelsize=13:antialias=true" \
	-f "osaka_unicode:style=Regular:pixelsize=13:antialias=true" \
	-a 32 -u 2 -n "$PANEL_WM_NAME" -g ${PANEL_WIDTH}x$PANEL_HEIGHT -F "$fgcolor" -B "$bgcolor" | sh - &

pgrep stalonetray &>/dev/null && pkill -9 stalonetray # it often doesn't actually exit with a SIGTERM so we use SIGKILL
runTray &
grep -q 'URxvt\*background' <(xrdb -query) && transset-df -i $(xdo id -N stalonetray -m) 0.85 &>/dev/null

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
wid=$(xdo id -m -a "stalonetray")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

trap "kill -TERM $(jobs -p | tr '\n' ' ')" 0 2 9 15

wait
