#!/bin/bash


DiskUsage() {
	while true
	do
		Mdot2Size="$(df | grep -e "/dev/nvme0n1p2" | sed "s/  */ /g")"
		hddSize="$(df | grep -e "/dev/sd[a-z][0-9]" | sed "s/  */ /g")"
		sizesTotal="$(echo "$hddSize" | cut -d" " -f2)"
		sizesUsed="$(echo "$hddSize" | cut -d" " -f3)"
		sizesAvail="$(echo "$hddSize" | cut -d" " -f4)"
		sizeTotalArray=( $sizesTotal )
		sizeUsedArray=( $sizesUsed )
		sizeAvailArray=( $sizesAvail )
		sumTotal="0"
		sumUsed="0"
		sumAvail="0"
		(( lengthArray="${#sizeUsedArray[@]}" ))
		(( i = 0 ))
		while (( i < "$lengthArray" ))
		do
			sumTotal="$(echo "${sizeTotalArray[$i]} + $sumTotal" | bc)"
			sumUsed="$(echo "${sizeUsedArray[$i]} + $sumUsed" | bc)"
			sumAvail="$(echo "${sizeAvailArray[$i]} + $sumAvail" | bc)"
			(( i++ ))
		done
		set -x
		if (( ${#sumTotal} > 9 )); then
			sumTotal="$(echo "scale=2; $sumTotal / 1024 / 1024 / 1024" | bc -l)TB"
		elif (( ${#sumTotal} > 6 )); then
			sumTotal="$(echo "scale=2; $sumTotal / 1024 / 1024" | bc -l)GB"
		elif (( ${#sumTotal} > 3 )); then
			sumTotal="$(echo "scale=2; $sumTotal / 1024" | bc -l)MB"
		fi
		if (( ${#sumUsed} > 9 )); then
			sumUsed="$(echo "scale=2; $sumUsed / 1024 / 1024 / 1024" | bc -l)TB"
		elif (( ${#sumUsed} > 6 )); then
			sumUsed="$(echo "scale=2; $sumUsed / 1024 / 1024" | bc -l)GB"
		elif (( ${#sumTotal} > 3 )); then
			sumUsed="$(echo "scale=2; $sumUsed / 1024" | bc -l)MB"
		fi
		if (( ${#sumAvail} > 9 )); then
			sumAvail="$(echo "scale=2; $sumAvail / 1024 / 1024 / 1024" | bc -l)TB"
		elif (( ${#sumTotal} > 6 )); then
			sumAvail="$(echo "scale=2; $sumAvail / 1024 / 1024" | bc -l)GB"
		elif (( ${#sumTotal} > 3 )); then
			sumAvail="$(echo "scale=2; $sumAvail / 1024" | bc -l)MB"
		fi
		echo  -e "DUsed size: ${sumUsed} of ${sumTotal}, ${sumAvail} left"

		sleep 10
	done
}

DiskUsage
