#!/bin/bash
windowName="$1"

if [ -z "$windowName" ] 
then
	echo "scratch expects an argument" >> ~/temp
else
	case "$windowName" in
		"scratch")
			if tmux ls | grep scratch &>/dev/null; then
				tmux -2 attach -t scratch
			else
				tmux new-session -d -s scratch -n GOMUKS 'gomuks; bash'
				tmux new-window -d -n MAIL -t scratch: 'neomutt'
				tmux new-window -d -n CAL -t scratch: 'calcurse; bash'
				tmux new-window -d -t scratch:
				tmux -2 attach-session -t scratch
			fi
			;;
		"trackma")
			$SHELL -c trackma
			;;
		"desktop")
			$SHELL 
			;;
		"files")
			if tmux ls | grep files &>/dev/null; then
				tmux -2 attach -t files
			else
				$SHELL -c 'tmux new-session -s files 'lf;bash''
			fi
			;;
		*)
			notify-send "Invalid windowName"
			;;
	esac
fi
