#!/bin/bash
windowName="$1"

if [ -z "$windowName" ] 
then
	echo "scratch expects an argument" >> ~/temp
else
	case "$windowName" in
		"scratch")
			if tmux ls | grep scratch &>/dev/null; then
				tmux -2 attach -t scratch
			else
				tmux new-session -d -s scratch -n GOMUKS 'gomuks; bash'
				tmux new-window -d -n MAIL -t scratch: 'neomutt; bash'
				tmux new-window -d -n CAL -t scratch: 'calcurse; bash'
				if grep -q MJ12 /etc/hostname; then
					running="$(sudo lxc-ls --fancy | grep RUNNING | cut -d" " -f1)"
					if [[ -z "$running" ]]; then
						tmux new-window -d -t scratch -n SHELL 'sudo lxc-start -n vpn; bash'
					else
						tmux new-window -d -t scratch -n SHELL 'bash'
					fi
					tmux splitw -d -v -t scratch:SHELL 'bluetoothctl'
				else
					tmux new-window -d -t scratch 'bash'
				fi
				tmux -2 attach-session -t scratch
			fi
			;;
		"trackma")
			$SHELL -c trackma
			;;
		"desktop")
			$SHELL 
			;;
		"files")
			if tmux ls | grep files &>/dev/null; then
				tmux -2 attach -t files
			else
				$SHELL -c 'tmux new-session -s files 'lf;bash''
			fi
			;;
		*)
			notify-send "Invalid windowName"
			;;
	esac
fi
