#!/bin/bash

site="$@"
filename="$(wget -qO- "$site" | grep -oe '<title>.*<\/title>' | sed -E -n 's/<title>(.*)<\/title>/\1/p').mkv"
(( i = 0 ))
while [[ -e "$filename" ]]
do
	filename="$(wget -qO- $site  | grep -oe '<title>.*<\/title>' | sed -E -n 's/<title>(.*)<\/title>/\1/p')$i.mkv"
	(( i++ ))
done

youtube-dl -o - "$site" | tee "$filename" | mpv --volume=30 -
