#!/bin/bash

cwd="$(pwd)/$1"
if tmux ls | grep DEV &>/dev/null; then
	if ! [ -d "$cwd" ]; then
		tmux -2 attach -t DEV:PRG
	else
		tmux -2 attach -t DEV:PRG -c "$cwd"
	fi
else
	if ! [ -d "$cwd" ]; then
		echo "Invalid directory!"
		exit 1
	fi

	tmux new-session -d -s DEV -n PRG -c "$cwd"
	tmux splitw -d -h -p 10 -t DEV:PRG -c "$cwd"
	tmux splitw -d -v -p 15 -t DEV:PRG.{right} -c "$cwd"
	tmux new-window -d -n FM -t DEV: "lf $cwd"
	tmux -2 attach-session -t DEV
fi
