#!/bin/bash
if (( $# != 1 )); then echo "ONE ARGUMENT IS REQUIRED!!1!11!"; exit 1; fi
imageExtensions="png jpg jpeg jpe jp2"
vidExtensions="mkv mp4 webm gif"
audioExtensions="mp3 flac opus"
docExtensions="pdf djvu epub"

url="$1"

extension="$(echo "$url" | sed -E "s/http.*\:\/\/.*\.([A-Za-z0-9]{1,})(\?[^.]+)*$/\1/")"

processImage() {
	curl -s --output - "$url" > /tmp/.image
	nohup sxiv -a /tmp/.image &>/dev/null &
}

processVideo() {
	if [ "$extension" = 'gif' ]; then nohup mpv --loop "$url" &>/dev/null &
	else nohup mpv "$url" &>/dev/null & 
	fi 
}

processAudio() {
	nohup mpv --audio-display=attachment --force-window --geometry=640x480 --profile=low-latency "$url" &>/dev/null &
}
processDocument() {
	curl -s --output - "$url" > /tmp/.document
	nohup zathura /tmp/.image &>/dev/null &
}
if echo "$url" | grep -qE "youtube\.com/watch|youtu\.be/[a-Z0-9]{11,}"; then 
	nohup mpv --ytdl-raw-options=add-metadata= "$url" &>/dev/null &
	exit 1
fi

if [[ "$extension" == "$url" ]]; then
	# check mimetypes since there's no usable extension to go by
	raw_mimetypes="$(curl -sI $url | grep -i "content-type:")"
	extension="$(curl -sI $url | grep -i "content-type:" | cut -d" " -f2- | cut -d"/" -f2 | tr -d '\r')"
fi
echo -e "URL is: $url\nExtension is $extension"
if echo "$imageExtensions"   | grep -iqw "$extension"; then echo in here; processImage
elif echo "$vidExtensions"   | grep -iqw "$extension"; then processVideo
elif echo "$audioExtensions" | grep -iqw "$extension"; then processAudio
elif echo "$docExtensions"   | grep -iqw "$extension"; then processDocument
else nohup qutebrowser "$url" &>/dev/null
fi
